# Generated by Django 5.1.7 on 2025-04-21 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('site', models.CharField(blank=True, max_length=128, null=True)),
                ('content', models.TextField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['time'], name='idx_time')],
            },
        ),
    ]
