# Generated by Django 5.1.7 on 2025-04-22 06:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=32)),
                ('que_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('que_text', models.TextField(default='no-content')),
                ('ans_time', models.DateTimeField(blank=True, null=True)),
                ('ans_text', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_ask',
                'indexes': [models.Index(fields=['que_time'], name='idx_que_time')],
            },
        ),
    ]
