# Generated by Django 5.1.7 on 2025-04-22 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mod_iamyukino', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ask',
            table=None,
        ),
    ]
