# Generated by Django 5.1.7 on 2025-04-24 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod_iamyukino', '0004_ask_authorip'),
    ]

    operations = [
        migrations.AddField(
            model_name='ask',
            name='autagent',
            field=models.CharField(default='unknown', max_length=64),
        ),
    ]
