# Generated by Django 5.1.7 on 2025-04-25 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod_iamyukino', '0005_ask_autagent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ask',
            name='que_text',
            field=models.TextField(),
        ),
    ]
