# Generated by Django 5.1.7 on 2025-05-05 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod_iamyukino', '0006_alter_ask_que_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ask',
            name='autagent',
            field=models.CharField(default='unknown', max_length=256),
        ),
    ]
